layout_spectrum: 0.2706356
typography_spectrum: 0.8962778
color:
  saturation: 0.4515421
  lightness: 0.716563
  brandStrength: 0.1433294
  rhythmicContrast: 0.7005221
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
name: GeorgeandGrace
